# Generated by Django 3.2 on 2021-04-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Juice', 'Juice'), ('Soda', 'Soda'), ('Milk', 'Milk')], max_length=10)),
            ],
        ),
    ]
