# Generated by Django 3.2 on 2021-04-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0002_auto_20210429_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='quantity',
        ),
        migrations.AddField(
            model_name='drink',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='type',
            field=models.TextField(default='Random'),
            preserve_default=False,
        ),
    ]
