# Generated by Django 3.2 on 2021-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyer',
            field=models.CharField(default='Name of buyer', max_length=20),
            preserve_default=False,
        ),
    ]
