# Generated by Django 3.2 on 2021-05-05 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoffeeShop', '0006_order_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
